# Updated : 2024.08.08
# Version : 1.1.1
# GitHub  : https://github.com/Sleeper85/esphome-junctek_khf

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  shunt_base: !include shunt_base.yaml
  shunt_combine: !include shunt_combine.yaml

external_components:
  - source: github://Sleeper85/esphome-junctek_khf@main
    refresh: 0s

uart:
  - id: !extend ${shunt_uart_id}
    baud_rate: 115200
    rx_buffer_size: 384

sensor:
  - platform: junctek_khf
    uart_id: ${shunt_uart_id}
    address: 1
    invert_current: false
    voltage:
      id: shunt${shunt_id}_voltage
      name: ${name} ${shunt_name} Voltage
    current:
      id: shunt${shunt_id}_current
      name: ${name} ${shunt_name} Current
    power:
      id: shunt${shunt_id}_power
      name: ${name} ${shunt_name} Power
    battery_level:
      id: shunt${shunt_id}_soc
      name: ${name} ${shunt_name} SoC
    temperature:
      name: ${name} ${shunt_name} Temperature
    charged_kwh:
      name: ${name} ${shunt_name} Charged Power
    discharged_kwh:
      name: ${name} ${shunt_name} Discharged Power
    battery_capacity_ah:
      name: ${name} ${shunt_name} Battery Capacity
    soc100_voltage:
      name: ${name} ${shunt_name} SoC 100% Voltage
    soc0_voltage:
      name: ${name} ${shunt_name} SoC 0% Voltage
    over_voltage_protection:
      name: ${name} ${shunt_name} Over Voltage Protection
    under_voltage_protection:
      name: ${name} ${shunt_name} Under Voltage Protection
    over_discharge_current_protection:
      name: ${name} ${shunt_name} Over Discharge Current Protection
    over_charge_current_protection:
      name: ${name} ${shunt_name} Over Charge Current Protection
    over_power_protection:
      name: ${name} ${shunt_name} Over Power Protection
    over_temperature_protection:
      name: ${name} ${shunt_name} Over Temperature Protection
    under_temperature_protection:
      name: ${name} ${shunt_name} Under Temperature Protection
