# Updated : 2024.08.08
# Version : 1.1.1
# GitHub  : https://github.com/KinDR007/VictronMPPT-ESPHOME

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  shunt_base: !include shunt_base.yaml
  shunt_combine: !include shunt_combine.yaml

external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
    refresh: 0s

uart:
  - id: !extend ${shunt_uart_id}
    baud_rate: 19200
    rx_buffer_size: 256

victron:
  uart_id: ${shunt_uart_id}
  id: victron0
  throttle: ${shunt_update_interval}

sensor:
  - platform: victron
    victron_id: victron0
    battery_voltage:
      id: shunt${shunt_id}_voltage
      name: "${name} ${shunt_name} battery voltage"
    auxiliary_battery_voltage:
      name: "${name} ${shunt_name} auxiliary battery voltage"
    midpoint_voltage_of_the_battery_bank:
      name: "${name} ${shunt_name} midpoint voltage of the battery bank"
    midpoint_deviation_of_the_battery_bank:
      name: "${name} ${shunt_name} midpoint deviation of the battery bank"
    battery_current:
      id: shunt${shunt_id}_current
      name: "${name} ${shunt_name} battery current"
    battery_temperature:
      name: "${name} ${shunt_name} battery temperature"
    instantaneous_power:
      id: shunt${shunt_id}_power
      name: "${name} ${shunt_name} instantaneous power"
    consumed_amp_hours:
      name: "${name} ${shunt_name} consumed amp hours"
    state_of_charge:
      id: shunt${shunt_id}_soc
      name: "${name} ${shunt_name} state of charge"
    time_to_go:
      name: "${name} ${shunt_name} time to go"
    depth_of_the_deepest_discharge:
      name: "${name} ${shunt_name} depth of the deepest discharge"
    depth_of_the_last_discharge:
      name: "${name} ${shunt_name} depth of the last discharge"
    depth_of_the_average_discharge:
      name: "${name} ${shunt_name} depth of the average discharge"
    number_of_charge_cycles:
      name: "${name} ${shunt_name} number of charge cycles"
    number_of_full_discharges:
      name: "${name} ${shunt_name} number of full discharges"
    cumulative_amp_hours_drawn:
      name: "${name} ${shunt_name} cumulative amp hours drawn"
    min_battery_voltage:
      name: "${name} ${shunt_name} min battery voltage"
    max_battery_voltage:
      name: "${name} ${shunt_name} max battery voltage"
    last_full_charge:
      name: "${name} ${shunt_name} last full charge"
    number_of_automatic_synchronizations:
      name: "${name} ${shunt_name} number of automatic synchronizations"
    number_of_low_main_voltage_alarms:
      name: "${name} ${shunt_name} number of low main voltage alarms"
    number_of_high_main_voltage_alarms:
      name: "${name} ${shunt_name} number of high main voltage alarms"
    number_of_low_auxiliary_voltage_alarms:
      name: "${name} ${shunt_name} number of low auxiliary voltage alarms"
    number_of_high_auxiliary_voltage_alarms:
      name: "${name} ${shunt_name} number of high auxiliary voltage alarms"
    min_auxiliary_battery_voltage:
      name: "${name} ${shunt_name} min auxiliary battery voltage"
    max_auxiliary_battery_voltage:
      name: "${name} ${shunt_name} max auxiliary battery voltage"
    amount_of_discharged_energy:
      name: "${name} ${shunt_name} amount of discharged energy"
    amount_of_charged_energy:
      name: "${name} ${shunt_name} amount of charged energy"
    dc_monitor_mode_id:
      name: "${name} ${shunt_name} dc monitor mode id"

text_sensor:
  - platform: victron
    victron_id: victron0
    alarm_condition_active:
      name: "${name} ${shunt_name} alarm condition active"
    alarm_reason:
      name: "${name} ${shunt_name} alarm reason"
    model_description:
      name: "${name} ${shunt_name} model description"
    firmware_version:
      name: "${name} ${shunt_name} firmware version"
    device_type:
      name: "${name} ${shunt_name} device type"
    serial_number:
      name: "${name} ${shunt_name} serial number"
    dc_monitor_mode:
      name: "${name} ${shunt_name} dc monitor mode"

binary_sensor:
  - platform: victron
    victron_id: victron0
    relay_state:
      name: "${name} ${shunt_name} relay state"
