# Updated : 2024.07.17
# Version : 1.4.1
# GitHub  : https://github.com/txubelaxu/esphome-jk-bms

packages:
  bms_base: !include bms_base.yaml
  bms_combine: !include bms_combine.yaml

jk_rs485_bms:
  - id: bms${bms_id}
    rs485_address: ${bms_rs485_address}
    jk_rs485_sniffer_id: ${sniffer_id}
    update_interval: ${bms_update_interval}

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms${bms_id}
    precharging:
      name: "${name} ${bms_name} precharging"
    charging:
      id: bms${bms_id}_switch_charging
      name: "${name} ${bms_name} charging"
    discharging:
      id: bms${bms_id}_switch_discharging
      name: "${name} ${bms_name} discharging"
    balancing:
      id: bms${bms_id}_switch_balancing
      name: "${name} ${bms_name} balancing"
    emergency:
      name: "${name} ${bms_name} emergency"
    heating:
      name: "${name} ${bms_name} heating"
    display_always_on:
      name: "${name} ${bms_name} display_always_on"
    charging_float_mode:
      name: "${name} ${bms_name} charging float mode"
    timed_stored_data:
      name: "${name} ${bms_name} timed stored data"
    disable_temperature_sensors:
      name: "${name} ${bms_name} disable temperature sensors"
    smart_sleep_on:
      name: "${name} ${bms_name} smart sleep on"
    disable_pcl_module:
      name: "${name} ${bms_name} disable pcl module"
    gps_heartbeat:
      name: "${name} ${bms_name} gps heartbeat"
    port_selection:
      name: "${name} ${bms_name} port selection"
    special_charger:
      name: "${name} ${bms_name} special charger"

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms${bms_id}
    status_balancing:
      id: bms${bms_id}_equalizing
      name: "${name} ${bms_name} status balancing"
    status_precharging:
      name: "${name} ${bms_name} status precharging"
    status_charging:
      name: "${name} ${bms_name} status charging"
    status_discharging:
      name: "${name} ${bms_name} status discharging"
    status_online:
      name: "${name} ${bms_name} status online"
    status_heating:
      name: "${name} ${bms_name} status heating"

sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms${bms_id}
    balancing_direction:
      name: "${name} ${bms_name} balancing direction"
    cell_smart_sleep_voltage:
      name: "${name} ${bms_name} cell smart sleep voltage"
    cell_voltage_min:
      id: bms${bms_id}_min_cell_voltage
      name: "${name} ${bms_name} cell voltage min"
    cell_voltage_max:
      id: bms${bms_id}_max_cell_voltage
      name: "${name} ${bms_name} cell voltage max"
    cell_voltage_min_cell_number:
      id: bms${bms_id}_min_voltage_cell
      name: "${name} ${bms_name} cell voltage min cell number"
    cell_voltage_max_cell_number:
      id: bms${bms_id}_max_voltage_cell
      name: "${name} ${bms_name} cell voltage max cell number"
    cell_delta_voltage:
      name: "${name} ${bms_name} cell delta voltage"
    cell_average_voltage:
      name: "${name} ${bms_name} cell average voltage"
    cell_resistance_min:
      name: "${name} ${bms_name} cell resistance min"
    cell_resistance_max:
      name: "${name} ${bms_name} cell resistance max"
    cell_resistance_min_cell_number:
      name: "${name} ${bms_name} cell resistance min cell number"
    cell_resistance_max_cell_number:
      name: "${name} ${bms_name} cell resistance max cell number"
    battery_voltage:
      id: bms${bms_id}_total_voltage
      name: "${name} ${bms_name} battery voltage"
    battery_current:
      id: bms${bms_id}_current
      name: "${name} ${bms_name} battery current"
    battery_power:
      id: bms${bms_id}_power
      name: "${name} ${bms_name} battery power"
    battery_power_charging:
      id: bms${bms_id}_charging_power
      name: "${name} ${bms_name} battery power charging"
    battery_power_discharging:
      id: bms${bms_id}_discharging_power
      name: "${name} ${bms_name} battery power discharging"
    temperature_sensor_1:
      id: bms${bms_id}_temperature_sensor_1
      name: "${name} ${bms_name} temperature sensor 1"
    temperature_sensor_2:
      id: bms${bms_id}_temperature_sensor_2
      name: "${name} ${bms_name} temperature sensor 2"
    temperature_sensor_3:
      id: bms${bms_id}_temperature_sensor_3
      name: "${name} ${bms_name} temperature sensor 3"
    temperature_sensor_4:
      id: bms${bms_id}_temperature_sensor_4
      name: "${name} ${bms_name} temperature sensor 4"
    temperature_sensor_5:
      id: bms${bms_id}_temperature_sensor_5
      name: "${name} ${bms_name} temperature sensor 5"
    temperature_powertube:
      name: "${name} ${bms_name} temperature powertube"
    battery_capacity_state_of_charge:
      id: bms${bms_id}_state_of_charge
      name: "${name} ${bms_name} battery capacity state of charge"
    battery_capacity_remaining:
      id: bms${bms_id}_capacity_remaining_ah
      name: "${name} ${bms_name} battery capacity remaining"
    battery_capacity_total_setting:
      id: bms${bms_id}_battery_capacity
      name: "${name} ${bms_name} battery capacity total setting"
    charging_cycles:
      id: bms${bms_id}_charging_cycles
      name: "${name} ${bms_name} charging cycles"
    battery_capacity_total_charging_cycle:
      name: "${name} ${bms_name} battery capacity total charging cycle"
    battery_total_runtime:
      name: "${name} ${bms_name} battery total runtime"
    balancing_current:
      name: "${name} ${bms_name} balancing current"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      name: "${name} ${bms_name} errors bitmask"
    cell_count_settings:
      id: bms${bms_id}_cell_count
      name: "${name} ${bms_name} cell count settings"
    cell_count_real:
      name: "${name} ${bms_name} cell count real"
    cell_overvoltage_protection:
      id: bms${bms_id}_cell_ovp
      name: "${name} ${bms_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      id: bms${bms_id}_cell_ovpr
      name: "${name} ${bms_name} cell overvoltage protection recovery"
    balancing_trigger_voltage:
      id: bms${bms_id}_balance_trigger_voltage
      name: "${name} ${bms_name} balancing trigger voltage"
    cell_balancing_starting_voltage:
      name: "${name} ${bms_name} cell balancing starting voltage"
    max_balancing_current:
      name: "${name} ${bms_name} max balancing current"
    cell_soc100_voltage:
      name: "${name} ${bms_name} cell soc100 voltage"
    cell_soc0_voltage:
      name: "${name} ${bms_name} cell soc0 voltage"
    cell_undervoltage_protection:
      name: "${name} ${bms_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      id: bms${bms_id}_cell_uvpr
      name: "${name} ${bms_name} cell undervoltage protection recovery"
    cell_power_off_voltage:
      name: "${name} ${bms_name} cell power off voltage"
    max_charging_current:
      id: bms${bms_id}_max_charge_current
      name: "${name} ${bms_name} max charging current"
    max_discharging_current:
      id: bms${bms_id}_max_discharge_current
      name: "${name} ${bms_name} max discharging current"
    battery_total_alarms_count:     
      name: "${name} ${bms_name} battery total alarms count"
    battery_total_alarms_active:     
      name: "${name} ${bms_name} battery total alarms active"
    uart1_protocol_number:
      name: "${name} ${bms_name} uart1 protocol number"
    uart2_protocol_number:
      name: "${name} ${bms_name} uart2 protocol number"
    battery_soh_valuation:    
      name: "${name} ${bms_name} battery soh valuation"

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms${bms_id}
    errors:
      name: "${name} ${bms_name} errors"
    operation_status:
      name: "${name} ${bms_name} operation status"
    battery_type:
      name: "${name} ${bms_name} battery type"
    total_runtime_formatted:
      name: "${name} ${bms_name} total runtime formatted"
    info_vendorid:
      name: "${name} ${bms_name} info vendorid"
    info_hardware_version:
      name: "${name} ${bms_name} info hardware version"
    info_software_version:
      name: "${name} ${bms_name} info software version"
    info_device_name:
      name: "${name} ${bms_name} info device name"
    info_device_password:
      name: "${name} ${bms_name} info device password"
    network_nodes_available:
      name: "${name} ${bms_name} network nodes available"
    info_device_serial_number:
      name: "${name} ${bms_name} info device serial number"
    info_device_setup_passcode:
      name: "${name} ${bms_name} info device setup passcode"         
