# Updated : 2024.07.17
# Version : 1.4.2
# GitHub  : https://github.com/txubelaxu/esphome-jk-bms

packages:
  bms_base: !include bms_base.yaml
  bms_combine: !include bms_combine.yaml

jk_rs485_bms:
  - id: bms${bms_id}
    rs485_address: ${bms_rs485_address}
    jk_rs485_sniffer_id: ${sniffer_id}
    update_interval: ${bms_update_interval}

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms${bms_id}
    precharging:
      name: "${name} ${bms_name} precharging"
    charging:
      id: bms${bms_id}_switch_charging
      name: "${name} ${bms_name} charging"
    discharging:
      id: bms${bms_id}_switch_discharging
      name: "${name} ${bms_name} discharging"
    balancing:
      id: bms${bms_id}_switch_balancing
      name: "${name} ${bms_name} balancing"
    emergency:
      name: "${name} ${bms_name} emergency"
    heating:
      name: "${name} ${bms_name} heating"
    display_always_on:
      name: "${name} ${bms_name} display_always_on"
    charging_float_mode:
      name: "${name} ${bms_name} charging float mode"
    timed_stored_data:
      name: "${name} ${bms_name} timed stored data"
    disable_temperature_sensors:
      name: "${name} ${bms_name} disable temperature sensors"
    smart_sleep_on:
      name: "${name} ${bms_name} smart sleep on"
    disable_pcl_module:
      name: "${name} ${bms_name} disable pcl module"
    gps_heartbeat:
      name: "${name} ${bms_name} gps heartbeat"
    port_selection:
      name: "${name} ${bms_name} port selection"
    special_charger:
      name: "${name} ${bms_name} special charger"

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms${bms_id}
    status_balancing:
      id: bms${bms_id}_equalizing
      name: "${name} ${bms_name} status balancing"
    status_precharging:
      name: "${name} ${bms_name} status precharging"
    status_charging:
      name: "${name} ${bms_name} status charging"
    status_discharging:
      name: "${name} ${bms_name} status discharging"
    status_online:
      name: "${name} ${bms_name} status online"
    status_heating:
      name: "${name} ${bms_name} status heating"
    alarm_wireres:
      name: "${name} ${bms_name} alarm WireRes"
    alarm_mosotp:
      name: "${name} ${bms_name} alarm MosOTP"
    alarm_cellquantity:
      name: "${name} ${bms_name} alarm CellQuantity"
    alarm_cursensorerr:
      name: "${name} ${bms_name} alarm CurSensorErr"
    alarm_cellovp:
      name: "${name} ${bms_name} alarm CellOVP"
    alarm_batovp:
      name: "${name} ${bms_name} alarm BatOVP"
    alarm_chocp:
      name: "${name} ${bms_name} alarm ChOCP"
    alarm_chscp:
      name: "${name} ${bms_name} alarm ChSCP"
    alarm_chotp:
      name: "${name} ${bms_name} alarm ChOTP"
    alarm_chutp:
      name: "${name} ${bms_name} alarm ChUTP"
    alarm_cpuauxcommuerr:
      name: "${name} ${bms_name} alarm CPUAuxCommuErr"
    alarm_celluvp:
      name: "${name} ${bms_name} alarm CellUVP"
    alarm_batuvp:
      name: "${name} ${bms_name} alarm BatUVP"
    alarm_dchocp:
      name: "${name} ${bms_name} alarm DchOCP"
    alarm_dchscp:
      name: "${name} ${bms_name} alarm DchSCP"
    alarm_dchotp:
      name: "${name} ${bms_name} alarm DchOTP"
    alarm_chargemos:
      name: "${name} ${bms_name} alarm ChargeMOS"
    alarm_dischargemos:
      name: "${name} ${bms_name} alarm DischargeMOS"
    alarm_gpsdisconneted:
      name: "${name} ${bms_name} alarm GPSDisconneted"
    alarm_modifypwdintime:
      name: "${name} ${bms_name} alarm ModifyPWDinTime"
    alarm_dischargeonfailed:
      name: "${name} ${bms_name} alarm DischargeOnFailed"
    alarm_batteryovertemp:
      name: "${name} ${bms_name} alarm BatteryOverTemp"
    alarm_temperaturesensoranomaly:
      name: "${name} ${bms_name} alarm TemperatureSensorAnomaly"
    alarm_plcmoduleanomaly:
      name: "${name} ${bms_name} alarm PLCModuleAnomaly"
    alarm_mostempsensorabsent:
      name: "${name} ${bms_name} alarm MOSTempSensorAbsent"
    alarm_battempsensor1absent:
      name: "${name} ${bms_name} alarm BATTempSensor1Absent"
    alarm_battempsensor2absent:
      name: "${name} ${bms_name} alarm BATTempSensor2Absent"
    alarm_battempsensor3absent:
      name: "${name} ${bms_name} alarm BATTempSensor3Absent"
    alarm_battempsensor4absent:
      name: "${name} ${bms_name} alarm BATTempSensor4Absent"
    alarm_battempsensor5absent:
      name: "${name} ${bms_name} alarm BATTempSensor5Absent"

sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms${bms_id}
    balancing_direction:
      name: "${name} ${bms_name} balancing direction"
    cell_smart_sleep_voltage:
      name: "${name} ${bms_name} cell smart sleep voltage"
    cell_voltage_min:
      id: bms${bms_id}_min_cell_voltage
      name: "${name} ${bms_name} cell voltage min"
    cell_voltage_max:
      id: bms${bms_id}_max_cell_voltage
      name: "${name} ${bms_name} cell voltage max"
    cell_voltage_min_cell_number:
      id: bms${bms_id}_min_voltage_cell
      name: "${name} ${bms_name} cell voltage min cell number"
    cell_voltage_max_cell_number:
      id: bms${bms_id}_max_voltage_cell
      name: "${name} ${bms_name} cell voltage max cell number"
    cell_delta_voltage:
      name: "${name} ${bms_name} cell delta voltage"
    cell_average_voltage:
      name: "${name} ${bms_name} cell average voltage"
    cell_resistance_min:
      name: "${name} ${bms_name} cell resistance min"
    cell_resistance_max:
      name: "${name} ${bms_name} cell resistance max"
    cell_resistance_min_cell_number:
      name: "${name} ${bms_name} cell resistance min cell number"
    cell_resistance_max_cell_number:
      name: "${name} ${bms_name} cell resistance max cell number"
    cell_voltage_01:
      name: "${name} ${bms_name} cell voltage 01"
    cell_voltage_02:
      name: "${name} ${bms_name} cell voltage 02"
    cell_voltage_03:
      name: "${name} ${bms_name} cell voltage 03"
    cell_voltage_04:
      name: "${name} ${bms_name} cell voltage 04"
    cell_voltage_05:
      name: "${name} ${bms_name} cell voltage 05"
    cell_voltage_06:
      name: "${name} ${bms_name} cell voltage 06"
    cell_voltage_07:
      name: "${name} ${bms_name} cell voltage 07"
    cell_voltage_08:
      name: "${name} ${bms_name} cell voltage 08"
    cell_voltage_09:
      name: "${name} ${bms_name} cell voltage 09"
    cell_voltage_10:
      name: "${name} ${bms_name} cell voltage 10"
    cell_voltage_11:
      name: "${name} ${bms_name} cell voltage 11"
    cell_voltage_12:
      name: "${name} ${bms_name} cell voltage 12"
    cell_voltage_13:
      name: "${name} ${bms_name} cell voltage 13"
    cell_voltage_14:
      name: "${name} ${bms_name} cell voltage 14"
    cell_voltage_15:
      name: "${name} ${bms_name} cell voltage 15"
    cell_voltage_16:
      name: "${name} ${bms_name} cell voltage 16"
    # cell_voltage_17:
    #   name: "${name} ${bms_name} cell voltage 17"
    # cell_voltage_18:
    #   name: "${name} ${bms_name} cell voltage 18"
    # cell_voltage_19:
    #   name: "${name} ${bms_name} cell voltage 19"
    # cell_voltage_20:
    #   name: "${name} ${bms_name} cell voltage 20"
    # cell_voltage_21:
    #   name: "${name} ${bms_name} cell voltage 21"
    # cell_voltage_22:
    #   name: "${name} ${bms_name} cell voltage 22"
    # cell_voltage_23:
    #   name: "${name} ${bms_name} cell voltage 23"
    # cell_voltage_24:
    #   name: "${name} ${bms_name} cell voltage 24"
    cell_resistance_01:
      name: "${name} ${bms_name} cell resistance 01"
    cell_resistance_02:
      name: "${name} ${bms_name} cell resistance 02"
    cell_resistance_03:
      name: "${name} ${bms_name} cell resistance 03"
    cell_resistance_04:
      name: "${name} ${bms_name} cell resistance 04"
    cell_resistance_05:
      name: "${name} ${bms_name} cell resistance 05"
    cell_resistance_06:
      name: "${name} ${bms_name} cell resistance 06"
    cell_resistance_07:
      name: "${name} ${bms_name} cell resistance 07"
    cell_resistance_08:
      name: "${name} ${bms_name} cell resistance 08"
    cell_resistance_09:
      name: "${name} ${bms_name} cell resistance 09"
    cell_resistance_10:
      name: "${name} ${bms_name} cell resistance 10"
    cell_resistance_11:
      name: "${name} ${bms_name} cell resistance 11"
    cell_resistance_12:
      name: "${name} ${bms_name} cell resistance 12"
    cell_resistance_13:
      name: "${name} ${bms_name} cell resistance 13"
    cell_resistance_14:
      name: "${name} ${bms_name} cell resistance 14"
    cell_resistance_15:
      name: "${name} ${bms_name} cell resistance 15"
    cell_resistance_16:
      name: "${name} ${bms_name} cell resistance 16"
    # cell_resistance_17:
    #   name: "${name} ${bms_name} cell resistance 17"
    # cell_resistance_18:
    #   name: "${name} ${bms_name} cell resistance 18"
    # cell_resistance_19:
    #   name: "${name} ${bms_name} cell resistance 19"
    # cell_resistance_20:
    #   name: "${name} ${bms_name} cell resistance 20"
    # cell_resistance_21:
    #   name: "${name} ${bms_name} cell resistance 21"
    # cell_resistance_22:
    #   name: "${name} ${bms_name} cell resistance 22"
    # cell_resistance_23:
    #   name: "${name} ${bms_name} cell resistance 23"
    # cell_resistance_24:
    #   name: "${name} ${bms_name} cell resistance 24"
    battery_voltage:
      id: bms${bms_id}_total_voltage
      name: "${name} ${bms_name} battery voltage"
    battery_current:
      id: bms${bms_id}_current
      name: "${name} ${bms_name} battery current"
    battery_power:
      id: bms${bms_id}_power
      name: "${name} ${bms_name} battery power"
    battery_power_charging:
      id: bms${bms_id}_charging_power
      name: "${name} ${bms_name} battery power charging"
    battery_power_discharging:
      id: bms${bms_id}_discharging_power
      name: "${name} ${bms_name} battery power discharging"
    temperature_sensor_1:
      id: bms${bms_id}_temperature_sensor_1
      name: "${name} ${bms_name} temperature sensor 1"
    temperature_sensor_2:
      id: bms${bms_id}_temperature_sensor_2
      name: "${name} ${bms_name} temperature sensor 2"
    temperature_sensor_3:
      id: bms${bms_id}_temperature_sensor_3
      name: "${name} ${bms_name} temperature sensor 3"
    temperature_sensor_4:
      id: bms${bms_id}_temperature_sensor_4
      name: "${name} ${bms_name} temperature sensor 4"
    temperature_sensor_5:
      id: bms${bms_id}_temperature_sensor_5
      name: "${name} ${bms_name} temperature sensor 5"
    temperature_powertube:
      name: "${name} ${bms_name} temperature powertube"
    battery_capacity_state_of_charge:
      id: bms${bms_id}_state_of_charge
      name: "${name} ${bms_name} battery capacity state of charge"
    battery_capacity_remaining:
      id: bms${bms_id}_capacity_remaining_ah
      name: "${name} ${bms_name} battery capacity remaining"
    battery_capacity_total_setting:
      id: bms${bms_id}_battery_capacity
      name: "${name} ${bms_name} battery capacity total setting"
    charging_cycles:
      id: bms${bms_id}_charging_cycles
      name: "${name} ${bms_name} charging cycles"
    battery_capacity_total_charging_cycle:
      name: "${name} ${bms_name} battery capacity total charging cycle"
    battery_total_runtime:
      name: "${name} ${bms_name} battery total runtime"
    balancing_current:
      name: "${name} ${bms_name} balancing current"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      name: "${name} ${bms_name} errors bitmask"
    cell_count_settings:
      id: bms${bms_id}_cell_count
      name: "${name} ${bms_name} cell count settings"
    cell_count_real:
      name: "${name} ${bms_name} cell count real"
    cell_overvoltage_protection:
      id: bms${bms_id}_cell_ovp
      name: "${name} ${bms_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      id: bms${bms_id}_cell_ovpr
      name: "${name} ${bms_name} cell overvoltage protection recovery"
    cell_request_charge_voltage:
      name: "${name} ${bms_name} cell request charge voltage"
    cell_request_charge_voltage_time:
      name: "${name} ${bms_name} cell request charge voltage time"
    cell_request_float_voltage:
      name: "${name} ${bms_name} cell request float voltage"
    cell_request_float_voltage_time:
      name: "${name} ${bms_name} cell request float voltage time"
    balancing_trigger_voltage:
      id: bms${bms_id}_balance_trigger_voltage
      name: "${name} ${bms_name} balancing trigger voltage"
    cell_balancing_starting_voltage:
      name: "${name} ${bms_name} cell balancing starting voltage"
    max_balancing_current:
      name: "${name} ${bms_name} max balancing current"
    cell_soc100_voltage:
      name: "${name} ${bms_name} cell soc100 voltage"
    cell_soc0_voltage:
      name: "${name} ${bms_name} cell soc0 voltage"
    cell_undervoltage_protection:
      name: "${name} ${bms_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      id: bms${bms_id}_cell_uvpr
      name: "${name} ${bms_name} cell undervoltage protection recovery"
    cell_power_off_voltage:
      name: "${name} ${bms_name} cell power off voltage"
    smart_sleep_time:
      name: "${name} ${bms_name} smart sleep time"
    max_charging_current:
      id: bms${bms_id}_max_charge_current
      name: "${name} ${bms_name} max charging current"
    max_discharging_current:
      id: bms${bms_id}_max_discharge_current
      name: "${name} ${bms_name} max discharging current"
    charging_overcurrent_protection_delay:
      name: "${name} ${bms_name} charging overcurrent protection delay"
    charging_overcurrent_protection_recovery_delay:
      name: "${name} ${bms_name} charging overcurrent protection recovery delay"
    discharging_overcurrent_protection_delay:
      name: "${name} ${bms_name} discharging overcurrent protection delay"
    discharging_overcurrent_protection_recovery_delay:
      name: "${name} ${bms_name} discharging overcurrent protection recovery delay"
    short_circuit_protection_delay:
      name: "${name} ${bms_name} short circuit protection delay"
    short_circuit_protection_recovery_delay:
      name: "${name} ${bms_name} short circuit protection recovery delay"
    precharging_time_from_discharge:
      name: "${name} ${bms_name} precharging time from discharge"
    charging_overtemperature_protection:
      name: "${name} ${bms_name} charging overtemperature protection"
    charging_overtemperature_protection_recovery:
      name: "${name} ${bms_name} charging overtemperature protection recovery"
    discharging_overtemperature_protection:
      name: "${name} ${bms_name} discharging overtemperature protection"
    discharging_overtemperature_protection_recovery:
      name: "${name} ${bms_name} discharging overtemperature protection recovery"
    charging_lowtemperature_protection:
      name: "${name} ${bms_name} charging lowtemperature protection"
    charging_lowtemperature_protection_recovery:
      name: "${name} ${bms_name} charging lowtemperature protection recovery"
    mos_overtemperature_protection:
      name: "${name} ${bms_name} mos overtemperature protection"
    mos_overtemperature_protection_recovery:
      name: "${name} ${bms_name} mos overtemperature protection recovery"
    powertube_temperature_protection:
      name: "${name} ${bms_name} powertube temperature protection"
    powertube_temperature_protection_recovery:
      name: "${name} ${bms_name} powertube temperature protection recovery"
    battery_total_alarms_count:     
      name: "${name} ${bms_name} battery total alarms count"
    battery_total_alarms_active:     
      name: "${name} ${bms_name} battery total alarms active"
    emergency_time_countdown:
      name: "${name} ${bms_name} emergency time countdown"
    uart1_protocol_number:
      name: "${name} ${bms_name} uart1 protocol number"
    uart2_protocol_number:
      name: "${name} ${bms_name} uart2 protocol number"
    battery_soh_valuation:    
      name: "${name} ${bms_name} battery soh valuation"
    discharging_overcurrent_protection_release_time:    
      name: "${name} ${bms_name} discharging overcurrent protection release time"
    discharging_short_circuit_protection_release_time:    
      name: "${name} ${bms_name} discharging short circuit protection release time"
    charging_overcurrent_protection_release_time:    
      name: "${name} ${bms_name} charging overcurrent protection release time"
    charging_short_circuit_protection_release_time:    
      name: "${name} ${bms_name} charging short circuit protection release time"
    cell_undervoltage_protection_release_time:    
      name: "${name} ${bms_name} cell undervoltage protection release time"
    cell_overvoltage_protection_release_time:    
      name: "${name} ${bms_name} cell overvoltage protection release time"

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms${bms_id}
    errors:
      name: "${name} ${bms_name} errors"
    operation_status:
      name: "${name} ${bms_name} operation status"
    battery_type:
      name: "${name} ${bms_name} battery type"
    total_runtime_formatted:
      name: "${name} ${bms_name} total runtime formatted"
    info_vendorid:
      name: "${name} ${bms_name} info vendorid"
    info_hardware_version:
      name: "${name} ${bms_name} info hardware version"
    info_software_version:
      name: "${name} ${bms_name} info software version"
    info_device_name:
      name: "${name} ${bms_name} info device name"
    info_device_password:
      name: "${name} ${bms_name} info device password"
    network_nodes_available:
      name: "${name} ${bms_name} network nodes available"
    info_device_serial_number:
      name: "${name} ${bms_name} info device serial number"
    info_device_setup_passcode:
      name: "${name} ${bms_name} info device setup passcode"         
