# Updated : 2024.07.13
# Version : 1.3.2
# GitHub  : https://github.com/syssi/esphome-jk-bms

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  bms_base: !include bms_base.yaml
  bms_combine: !include bms_combine.yaml

external_components:
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s

# +--------------------------------------+
# | JK-BMS UART connection               |
# +--------------------------------------+

jk_modbus:
  - id: modbus_bms${bms_id}
    uart_id: ${bms_uart_id}

jk_bms:
  - id: bms${bms_id}
    jk_modbus_id: modbus_bms${bms_id}
    update_interval: ${bms_update_interval}

# +--------------------------------------+

binary_sensor:
  - platform: jk_bms
    jk_bms_id: bms${bms_id}
    balancing:
      id: bms${bms_id}_equalizing
      name: "${name} ${bms_name} balancing"
    balancing_switch:
      id: bms${bms_id}_switch_balancing
      name: "${name} ${bms_name} balancing switch"
    charging:
      name: "${name} ${bms_name} charging"
    charging_switch:
      id: bms${bms_id}_switch_charging
      name: "${name} ${bms_name} charging switch"
    discharging:
      name: "${name} ${bms_name} discharging"
    discharging_switch:
      id: bms${bms_id}_switch_discharging
      name: "${name} ${bms_name} discharging switch"
    dedicated_charger_switch:
      name: "${name} ${bms_name} dedicated charger switch"

switch:
  - platform: jk_bms
    jk_bms_id: bms${bms_id}
    charging:
      name: "${name} ${bms_name} Charge switch"
    discharging:
      name: "${name} ${bms_name} Discharge switch"
    # Do not uncomment unless balancer switch over UART starts working in the future
    # balancer:
    #   id: bms${bms_id}_switch_balancing
    #   name: "${name} ${bms_name} Balance switch"

sensor:
  - platform: jk_bms
    jk_bms_id: bms${bms_id}
    min_cell_voltage:
      id: bms${bms_id}_min_cell_voltage
      name: "${name} ${bms_name} min cell voltage"
    max_cell_voltage:
      id: bms${bms_id}_max_cell_voltage
      name: "${name} ${bms_name} max cell voltage"
    min_voltage_cell:
      id: bms${bms_id}_min_voltage_cell
      name: "${name} ${bms_name} min voltage cell"
    max_voltage_cell:
      id: bms${bms_id}_max_voltage_cell
      name: "${name} ${bms_name} max voltage cell"
    delta_cell_voltage:
      id: bms${bms_id}_delta_cell_voltage
      name: "${name} ${bms_name} delta cell voltage"
    average_cell_voltage:
      name: "${name} ${bms_name} average cell voltage"
    cell_voltage_1:
      id: bms${bms_id}_cell_v_01
      name: "${name} ${bms_name} cell voltage 01"
    cell_voltage_2:
      id: bms${bms_id}_cell_v_02
      name: "${name} ${bms_name} cell voltage 02"
    cell_voltage_3:
      id: bms${bms_id}_cell_v_03
      name: "${name} ${bms_name} cell voltage 03"
    cell_voltage_4:
      id: bms${bms_id}_cell_v_04
      name: "${name} ${bms_name} cell voltage 04"
    cell_voltage_5:
      id: bms${bms_id}_cell_v_05
      name: "${name} ${bms_name} cell voltage 05"
    cell_voltage_6:
      id: bms${bms_id}_cell_v_06
      name: "${name} ${bms_name} cell voltage 06"
    cell_voltage_7:
      id: bms${bms_id}_cell_v_07
      name: "${name} ${bms_name} cell voltage 07"
    cell_voltage_8:
      id: bms${bms_id}_cell_v_08
      name: "${name} ${bms_name} cell voltage 08"
    cell_voltage_9:
      id: bms${bms_id}_cell_v_09
      name: "${name} ${bms_name} cell voltage 09"
    cell_voltage_10:
      id: bms${bms_id}_cell_v_10
      name: "${name} ${bms_name} cell voltage 10"
    cell_voltage_11:
      id: bms${bms_id}_cell_v_11
      name: "${name} ${bms_name} cell voltage 11"
    cell_voltage_12:
      id: bms${bms_id}_cell_v_12
      name: "${name} ${bms_name} cell voltage 12"
    cell_voltage_13:
      id: bms${bms_id}_cell_v_13
      name: "${name} ${bms_name} cell voltage 13"
    cell_voltage_14:
      id: bms${bms_id}_cell_v_14
      name: "${name} ${bms_name} cell voltage 14"
    cell_voltage_15:
      id: bms${bms_id}_cell_v_15
      name: "${name} ${bms_name} cell voltage 15"
    cell_voltage_16:
      id: bms${bms_id}_cell_v_16
      name: "${name} ${bms_name} cell voltage 16"
    cell_voltage_17:
      id: bms${bms_id}_cell_v_17
      name: "${name} ${bms_name} cell voltage 17"
      disabled_by_default: true
    cell_voltage_18:
      id: bms${bms_id}_cell_v_18
      name: "${name} ${bms_name} cell voltage 18"
      disabled_by_default: true
    cell_voltage_19:
      id: bms${bms_id}_cell_v_19
      name: "${name} ${bms_name} cell voltage 19"
      disabled_by_default: true
    cell_voltage_20:
      id: bms${bms_id}_cell_v_20
      name: "${name} ${bms_name} cell voltage 20"
      disabled_by_default: true
    cell_voltage_21:
      id: bms${bms_id}_cell_v_21
      name: "${name} ${bms_name} cell voltage 21"
      disabled_by_default: true
    cell_voltage_22:
      id: bms${bms_id}_cell_v_22
      name: "${name} ${bms_name} cell voltage 22"
      disabled_by_default: true
    cell_voltage_23:
      id: bms${bms_id}_cell_v_23
      name: "${name} ${bms_name} cell voltage 23"
      disabled_by_default: true
    cell_voltage_24:
      id: bms${bms_id}_cell_v_24
      name: "${name} ${bms_name} cell voltage 24"
      disabled_by_default: true
    power_tube_temperature:
      id: bms${bms_id}_power_tube_temperature
      name: "${name} ${bms_name} power tube temperature"
    temperature_sensor_1:
      id: bms${bms_id}_temperature_sensor_1
      name: "${name} ${bms_name} temperature sensor 1"
    temperature_sensor_2:
      id: bms${bms_id}_temperature_sensor_2
      name: "${name} ${bms_name} temperature sensor 2"
    total_voltage:
      id: bms${bms_id}_total_voltage
      name: "${name} ${bms_name} total voltage"
    current:
      id: bms${bms_id}_current
      name: "${name} ${bms_name} current"
    power:
      id: bms${bms_id}_power
      name: "${name} ${bms_name} power"
    charging_power:
      id: bms${bms_id}_charging_power
      name: "${name} ${bms_name} charging power"
    discharging_power:
      id: bms${bms_id}_discharging_power
      name: "${name} ${bms_name} discharging power"
    capacity_remaining:
      id: bms${bms_id}_state_of_charge
      name: "${name} ${bms_name} capacity remaining"
    capacity_remaining_derived:
      id: bms${bms_id}_capacity_remaining_ah
      name: "${name} ${bms_name} capacity remaining derived"
    temperature_sensors:
      name: "${name} ${bms_name} temperature sensors"
      entity_category: diagnostic
    charging_cycles:
      id: bms${bms_id}_charging_cycles
      name: "${name} ${bms_name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} ${bms_name} total charging cycle capacity"
    battery_strings:
      id: bms${bms_id}_cell_count
      name: "${name} ${bms_name} battery strings"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      name: "${name} ${bms_name} errors bitmask"
      entity_category: diagnostic
    operation_mode_bitmask:
      name: "${name} ${bms_name} operation mode bitmask"
      entity_category: diagnostic
    total_voltage_overvoltage_protection:
      name: "${name} ${bms_name} total voltage overvoltage protection"
    total_voltage_undervoltage_protection:
      name: "${name} ${bms_name} total voltage undervoltage protection"
      id: bms${bms_id}_total_uvp
    cell_voltage_overvoltage_protection:
      id: bms${bms_id}_cell_ovp
      name: "${name} ${bms_name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      id: bms${bms_id}_cell_ovpr
      name: "${name} ${bms_name} cell voltage overvoltage recovery"
    cell_voltage_overvoltage_delay:
      name: "${name} ${bms_name} cell voltage overvoltage delay"
    cell_voltage_undervoltage_protection:
      id: bms${bms_id}_cell_uvp
      name: "${name} ${bms_name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      id: bms${bms_id}_cell_uvpr
      name: "${name} ${bms_name} cell voltage undervoltage recovery"
    cell_voltage_undervoltage_delay:
      name: "${name} ${bms_name} cell voltage undervoltage delay"
    cell_pressure_difference_protection:
      name: "${name} ${bms_name} cell pressure difference protection"
    discharging_overcurrent_protection:
      id: bms${bms_id}_max_discharge_current
      name: "${name} ${bms_name} discharging overcurrent protection"
    discharging_overcurrent_delay:
      name: "${name} ${bms_name} discharging overcurrent delay"
    charging_overcurrent_protection:
      id: bms${bms_id}_max_charge_current
      name: "${name} ${bms_name} charging overcurrent protection"
    charging_overcurrent_delay:
      name: "${name} ${bms_name} charging overcurrent delay"
    balance_starting_voltage:
      id: bms${bms_id}_balance_starting_voltage
      name: "${name} ${bms_name} balance starting voltage"
    balance_opening_pressure_difference:
      id: bms${bms_id}_balance_trigger_voltage
      name: "${name} ${bms_name} balance opening pressure difference"
    power_tube_temperature_protection:
      name: "${name} ${bms_name} power tube temperature protection"
    power_tube_temperature_recovery:
      name: "${name} ${bms_name} power tube temperature recovery"
    temperature_sensor_temperature_protection:
      name: "${name} ${bms_name} temperature sensor temperature protection"
    temperature_sensor_temperature_recovery:
      name: "${name} ${bms_name} temperature sensor temperature recovery"
    temperature_sensor_temperature_difference_protection:
      name: "${name} ${bms_name} temperature sensor temperature difference protection"
    charging_high_temperature_protection:
      name: "${name} ${bms_name} charging high temperature protection"
    discharging_high_temperature_protection:
      name: "${name} ${bms_name} discharging high temperature protection"
    charging_low_temperature_protection:
      name: "${name} ${bms_name} charging low temperature protection"
    charging_low_temperature_recovery:
      name: "${name} ${bms_name} charging low temperature recovery"
    discharging_low_temperature_protection:
      name: "${name} ${bms_name} discharging low temperature protection"
    discharging_low_temperature_recovery:
      name: "${name} ${bms_name} discharging low temperature recovery"
    total_battery_capacity_setting:
      id: bms${bms_id}_battery_capacity
      name: "${name} ${bms_name} total battery capacity setting"
    current_calibration:
      name: "${name} ${bms_name} current calibration"
    device_address:
      name: "${name} ${bms_name} device address"
      entity_category: diagnostic
    sleep_wait_time:
      name: "${name} ${bms_name} sleep wait time"
      entity_category: diagnostic
      disabled_by_default: true
    alarm_low_volume:
      name: "${name} ${bms_name} alarm low volume"
      disabled_by_default: true
    manufacturing_date:
      name: "${name} ${bms_name} manufacturing date"
      entity_category: diagnostic
      disabled_by_default: true
    total_runtime:
      name: "${name} ${bms_name} total runtime"
      entity_category: diagnostic
    # start_current_calibration:
    #   name: "${name} ${bms_name} start current calibration"
    actual_battery_capacity:
      name: "${name} ${bms_name} actual battery capacity"
    # protocol_version:
    #   name: "${name} ${bms_name} protocol version"

text_sensor:
  - platform: jk_bms
    jk_bms_id: bms${bms_id}
    errors:
      name: "${name} ${bms_name} errors"
      entity_category: diagnostic
    operation_mode:
      name: "${name} ${bms_name} operation mode"
      entity_category: diagnostic
    battery_type:
      name: "${name} ${bms_name} battery type"
      entity_category: diagnostic
    # password:
    #   name: "${name} ${bms_name} password"
    device_type:
      name: "${name} ${bms_name} device type"
      entity_category: diagnostic
    software_version:
      name: "${name} ${bms_name} software version"
      entity_category: diagnostic
    manufacturer:
      name: "${name} ${bms_name} manufacturer"
      entity_category: diagnostic
    total_runtime_formatted:
      name: "${name} ${bms_name} total runtime formatted"
      entity_category: diagnostic
