# Updated : 2024.07.17
# Version : 1.4.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

globals:
  - id: bms${bms_id}_combined
    type: bool
    restore_value: no
    initial_value: "false"

switch:
# Combine Enable-Switch (user controlled switch to en/dis-able combine)
  - platform: template
    name: "${name} ${bms_name} Combine enabled"
    id: bms${bms_id}_switch_combine
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true

binary_sensor:
# Combine Availability (indicated, if the BMS is able to be included in combine)
  - platform: template
    name: "${name} ${bms_name} Combine Availability"
    id: bms${bms_id}_availability
    lambda: return (((id(bms${bms_id}_switch_charging).state) || (id(bms${bms_id}_switch_discharging).state)) && (id(bms${bms_id}_errors_bitmask).state == 0));

# Can be combined (indicated, if the BMS can be combined)
  - platform: template
    name: "${name} ${bms_name} Can be combined"
    id: bms${bms_id}_can_be_combined
    lambda: return ((id(bms${bms_id}_availability).state) && (id(bms${bms_id}_switch_combine).state));

# Combine once without conditions
esphome:
  on_boot:
    then:
      # BMS counter total
      - lambda: id(${yambms_id}_bms_counter) += 1;
      #- script.execute: my_script

interval:
  - interval: ${bms_combine_interval}
    then:
      - lambda: |-
          // Combine once, only if the device is able to be included in combine
          if (id(bms${bms_id}_can_be_combined).state) {

            if (id(bms${bms_id}_combined) == false) {
              // can_be_combined_bms_counter
              id(${yambms_id}_can_be_combined_bms_counter) += 1;
              
              // cell_count TOTAL
              id(${yambms_id}_total_cell_count) += id(bms${bms_id}_cell_count).state;
              
              // battery_capacity TOTAL
              id(${yambms_id}_total_battery_capacity) += id(bms${bms_id}_battery_capacity).state;
              
              // Combined
              id(bms${bms_id}_combined) = true;
            }
          }
          // Uncombine once
          else if (id(bms${bms_id}_combined) == true){

            // can_be_combined_bms_counter
            id(${yambms_id}_can_be_combined_bms_counter) -= 1;

            // cell_count TOTAL
            id(${yambms_id}_total_cell_count) -= id(bms${bms_id}_cell_count).state;

            // battery_capacity TOTAL
            id(${yambms_id}_total_battery_capacity) -= id(bms${bms_id}_battery_capacity).state;
            
            // Uncombined
            id(bms${bms_id}_combined) = false;
          }

          // Combine continuously
          if (id(${yambms_id}_combined_bms_counter) < id(${yambms_id}_bms_counter)) {

            // BMS errors ?
            if (id(bms${bms_id}_errors_bitmask).state > 1) {

              // errors_bitmask (16bit)
              uint16_t bms_errors_bitmask = id(bms${bms_id}_errors_bitmask).state;
              // Alarm - bitwise AND
              id(${yambms_id}_errors_bitmask_alarm_var) |= bms_errors_bitmask;
              // Warning - bitwise OR
              id(${yambms_id}_errors_bitmask_warning_var) |= bms_errors_bitmask;
              // errors_bitmask_counter
              id(${yambms_id}_errors_bitmask_counter_var) += 1;
            }

            // Combine only if the device is able to be included in combine
            else if (id(bms${bms_id}_can_be_combined).state) {

              // total_voltage TOTAL
              id(${yambms_id}_total_total_voltage) += id(bms${bms_id}_total_voltage).state;
              
              // current TOTAL
              id(${yambms_id}_total_current) += id(bms${bms_id}_current).state;
              
              // power TOTAL
              id(${yambms_id}_total_power) += id(bms${bms_id}_power).state;

              // max_charge_current TOTAL
              if (id(bms${bms_id}_switch_charging).state) id(${yambms_id}_total_max_charge_current) += id(bms${bms_id}_max_charge_current).state;
              
              // max_discharge_current TOTAL
              if (id(bms${bms_id}_switch_discharging).state) id(${yambms_id}_total_max_discharge_current) += id(bms${bms_id}_max_discharge_current).state;
              
              // capacity_remaining_ah TOTAL
              id(${yambms_id}_total_capacity_remaining_ah) += id(bms${bms_id}_capacity_remaining_ah).state;

              // soc MEAN
              id(${yambms_id}_total_soc) += id(bms${bms_id}_state_of_charge).state;
                            
              // charging_cycles MEAN
              id(${yambms_id}_total_charging_cycles) += id(bms${bms_id}_charging_cycles).state;

              // equalizing_counter TOTAL
              if (id(bms${bms_id}_equalizing).state) id(${yambms_id}_equalizing_counter) += 1;

              // bms_switch_charging_counter TOTAL
              if (id(bms${bms_id}_switch_charging).state) id(${yambms_id}_bms_switch_charging_counter) += 1;

              // bms_switch_discharging_counter TOTAL
              if (id(bms${bms_id}_switch_discharging).state) id(${yambms_id}_bms_switch_discharging_counter) += 1;
              
              // MIN/MAX values
              // balance_trigger_voltage MAX
              if (id(bms${bms_id}_balance_trigger_voltage).state > id(${yambms_id}_max_balance_trigger_voltage)) id(${yambms_id}_max_balance_trigger_voltage) = id(bms${bms_id}_balance_trigger_voltage).state;
              
              // min_cell_voltage MIN
              // min_voltage_cell MIN (cell number)
              if (id(bms${bms_id}_min_cell_voltage).state < id(${yambms_id}_min_min_cell_voltage)) {
                id(${yambms_id}_min_min_cell_voltage) = id(bms${bms_id}_min_cell_voltage).state;
                id(${yambms_id}_min_min_voltage_cell) = id(bms${bms_id}_min_voltage_cell).state + (${bms_id} * 100);
              }

              // max_cell_voltage MAX
              // max_voltage_cell MAX (cell number)
              if (id(bms${bms_id}_max_cell_voltage).state > id(${yambms_id}_max_max_cell_voltage)) {
                id(${yambms_id}_max_max_cell_voltage) = id(bms${bms_id}_max_cell_voltage).state;
                id(${yambms_id}_max_max_voltage_cell) = id(bms${bms_id}_max_voltage_cell).state + (${bms_id} * 100);
              }
              
              // cell_ovp MIN
              if (id(bms${bms_id}_cell_ovp).state < id(${yambms_id}_min_cell_ovp)) id(${yambms_id}_min_cell_ovp) = id(bms${bms_id}_cell_ovp).state;
              
              // cell_ovpr MIN
              if (id(bms${bms_id}_cell_ovpr).state < id(${yambms_id}_min_cell_ovpr)) id(${yambms_id}_min_cell_ovpr) = id(bms${bms_id}_cell_ovpr).state;
              
              // cell_uvpr MAX
              if (id(bms${bms_id}_cell_uvpr).state > id(${yambms_id}_max_cell_uvpr)) id(${yambms_id}_max_cell_uvpr) = id(bms${bms_id}_cell_uvpr).state;
              
              // temperature_sensor_1 MAX
              if (id(bms${bms_id}_temperature_sensor_1).state > id(${yambms_id}_max_temperature_sensor_1)) id(${yambms_id}_max_temperature_sensor_1) = id(bms${bms_id}_temperature_sensor_1).state;
              
              // temperature_sensor_2 MAX
              if (id(bms${bms_id}_temperature_sensor_2).state > id(${yambms_id}_max_temperature_sensor_2)) id(${yambms_id}_max_temperature_sensor_2) = id(bms${bms_id}_temperature_sensor_2).state;
            }
            
            // BMS combined counter
            id(${yambms_id}_combined_bms_counter) += 1;
          }