# Updated : 2024.07.28
# Version : 1.1.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

debug:
  update_interval: ${debug_update_interval}

text_sensor:
  - platform: debug
    device:
      name: ${name} ${debug_name} Device info
      id: ${debug_name}_device_info
    reset_reason:
      name: ${name} ${debug_name} Reset reason
      id: ${debug_name}_reset_reason

sensor:
  - platform: debug
    free:
      name: ${name} ${debug_name} Heap free
      id: ${debug_name}_heap_free
    block:
      name: ${name} ${debug_name} Heap max block
      id: ${debug_name}_heap_max_block
    psram:
      name: ${name} ${debug_name} Free PSRAM
      id: ${debug_name}_free_psram
    loop_time:
      name: ${name} ${debug_name} Loop time
      id: ${debug_name}_loop_time

  - platform: template
    name: ${name} ${debug_name} Heap free (%)
    id: ${debug_name}_heap_free_percent
    unit_of_measurement: '%'
    accuracy_decimals: 2
    icon: mdi:percent
    update_interval: ${debug_update_interval}
    entity_category: diagnostic
    # 524288 B (SRAM total)
    # 327680 B (DRAM usable)
    lambda: return ( id(${debug_name}_heap_free).state * 100 / 327680 );

  - platform: template
    name: ${name} ${debug_name} Heap max block (%)
    id: ${debug_name}_heap_max_block_percent
    unit_of_measurement: '%'
    accuracy_decimals: 2
    icon: mdi:percent
    update_interval: ${debug_update_interval}
    entity_category: diagnostic
    # 524288 B (SRAM total)
    # 327680 B (DRAM usable)
    lambda: return ( id(${debug_name}_heap_max_block).state * 100 / 327680 );

  - platform: template
    name: ${name} ${debug_name} Free PSRAM (%)
    id: ${debug_name}_free_psram_percent
    unit_of_measurement: '%'
    accuracy_decimals: 2
    icon: mdi:percent
    update_interval: ${debug_update_interval}
    entity_category: diagnostic
    lambda: return ( id(${debug_name}_free_psram).state * 100 / ${debug_psram_size} ); // 8388608
