# Updated : 2024.05.17
# Version : 1.1
# GitHub  : https://github.com/Sleeper85/esphome-jk-bms-can

esp32:
  board: m5stack-atom
  framework:
    type: arduino

esphome:
  on_boot:
    then:
      - light.turn_on:
          id: esp_light
          red: 50%
          blue: 50%
          green: 0%
          brightness: 50%

uart:
  # UART 1 : BMS 1
  - id: uart_esp_1
    tx_pin: 32
    rx_pin: 26
    baud_rate: 115200
    rx_buffer_size: 384 # 1000 with JK-BMS PB RS485

canbus:
  # CANBUS NODE 1
  - platform: esp32_can
    id: canbus_node1
    tx_pin: 22
    rx_pin: 19
    can_id: 1
    bit_rate: 500kbps

light:
  # https://esphome.io/components/light/esp32_rmt_led_strip
  - platform: esp32_rmt_led_strip
    id: esp_light
    name: ${name} ESP Light
    rgb_order: GRB
    pin: 27
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    entity_category: config
    internal: true
