# Updated : 2024.07.17
# Version : 1.4.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# Atom S3 Lite - SKU:C124
# https://docs.m5stack.com/en/core/AtomS3%20Lite
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

esphome:
  # Standard uses a single line for data, Dual IO uses 2 lines for data.
  platformio_options:
    board_build.flash_mode: dio # Needed to flash the ESP32-S3 and prevent reboot loop
  on_boot:
    then:
      - light.turn_on:
          id: esp_light
          red: 50%
          blue: 50%
          green: 0%
          brightness: 50%

logger:
  hardware_uart: USB_SERIAL_JTAG

uart:
  # UART 1
  - id: uart_esp_1
    tx_pin: 1
    rx_pin: 2
    baud_rate: 115200

canbus:
  # CANBUS NODE 1
  - platform: esp32_can
    id: canbus_node1
    tx_pin: 5
    rx_pin: 6
    can_id: 1
    bit_rate: 500kbps

light:
  # https://esphome.io/components/light/esp32_rmt_led_strip
  - platform: esp32_rmt_led_strip
    id: esp_light
    name: ${name} ESP Light
    rgb_order: GRB
    pin: 35
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    entity_category: config
    internal: true
