# Updated : 2024.08.28
# Version : 1.1.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  board_chip: "ESP32"
  board_name: "Atom Matrix"

# Atom Matrix - SKU:C008-B
# https://docs.m5stack.com/en/core/ATOM%20Matrix
esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

esphome:
  on_boot:
    then:
      - light.turn_on:
          id: esp_light
          red: 50%
          blue: 50%
          green: 0%
          brightness: 50%

uart:
  # UART 1
  - id: uart_esp_1
    tx_pin: 32
    rx_pin: 26
    baud_rate: 115200

canbus:
  # CANBUS NODE 1
  - platform: esp32_can
    id: canbus_node1
    tx_pin: 22
    rx_pin: 19
    can_id: 1
    bit_rate: 500kbps

light:
  # https://esphome.io/components/light/esp32_rmt_led_strip
  - platform: esp32_rmt_led_strip
    id: esp_light
    name: ${name} ESP Light
    rgb_order: GRB
    pin: 27
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    entity_category: config
    internal: true
