sensor:
  - platform: bmp280
    temperature:
      name: ${name}_${bmp_280_name}_temperature
      accuracy_decimals: 1
      oversampling: 16x
      id: ${bmp_280_name}_temperature
    pressure:
      name: ${name}_${bme_280_name}_pression
      accuracy_decimals: 1
      id: ${bmp_280_name}_pression
    address: ${bmp_280_address}
    update_interval: ${bmp_update_interval}
    i2c_id: ${bmp_280_i2c_bus}
