# Updated : 2024.05.17
# Version : 1.2.0
# GitHub  : https://github.com/txubelaxu/esphome-jk-bms
# Readme  : https://github.com/txubelaxu/esphome-jk-bms/blob/main/components/jk_rs485_bms/README.md

external_components:
 - source: github://txubelaxu/esphome-jk-bms@main
   refresh: 0s

jk_rs485_sniffer:
  - id: ${sniffer_id}
    protocol_version: ${sniffer_protocol}
    rx_timeout: 500ms
    uart_id: ${sniffer_uart_id}
    talk_pin: ${sniffer_talk_pin}
