
# *** These are the specific settings you need to change in the YAML if you use the Atom Lite ESP32-PICO board ***

# 1) Choose the configuration file you want to use:
#    - esp32_ble_jk-bms-can.yaml :  If you don't want to connect a wire between the BMS and the ESP32 choose the Bluetooth version.
#    - esp32_wire_jk-bms-can.yaml : If you prefer to use a wired connection between the BMS and the ESP32 choose the Wire version.

# 2) Edit the YAML file you have chosen with the information below :

# +--------------------------------------+
# | ESP32 CAN/serial port pins           |
# +--------------------------------------+
# GPIO pins your CAN bus transceiver ATOMIC CANBus Base (CA-IS3050G)
  can_tx_pin: GPIO22
  can_rx_pin: GPIO19
# GPIO pins your JK-BMS UART-TTL is connected to the grove port of Atom Lite
  tx_pin: GPIO32
  rx_pin: GPIO26

# +--------------------------------------+
# | ESP32 settings                       |
# +--------------------------------------+
# For a stable Bluetooth connection keep the "esp-idf" framework
esp32:
  board: m5stack-atom
  framework:
    type: arduino
