
# *** These are the specific settings you need to change in the YAML if you use the ESP32 DevKit v1 30 pin board ***

# 1) Choose the configuration file you want to use:
#    - esp32_ble_jk-bms-can.yaml :  If you don't want to connect a wire between the BMS and the ESP32 choose the Bluetooth version.
#    - esp32_wire_jk-bms-can.yaml : If you prefer to use a wired connection between the BMS and the ESP32 choose the Wire version.

# 2) Edit the YAML file you have chosen with the information below :

# +--------------------------------------+
# | ESP32 CAN/serial port pins           |
# +--------------------------------------+
# GPIO pins your CAN bus transceiver (TJA1050, TJA1051T or SN65HVD230) is connected to the ESP32 TX->TX and RX->RX !
  can_tx_pin: GPIO23
  can_rx_pin: GPIO22
# GPIO pins your JK-BMS UART-TTL is connected to the ESP32 TX->RX and RX->TX !
  tx_pin: GPIO17
  rx_pin: GPIO16

# +--------------------------------------+
# | ESP32 settings                       |
# +--------------------------------------+
# For a stable Bluetooth connection keep the "esp-idf" framework
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
