# Updated : 2024.05.18
# Version : 1.1
# GitHub  : https://github.com/Sleeper85/esphome-jk-bms-can

esp32:
  board: esp32dev
  framework:
    type: esp-idf

uart:
  # UART 0 : uart used for ESP32 flashing and logs, can be released if necessary (tx_pin: 1, rx_pin: 3)
  # UART 1 : JK-BMS 1
  - id: uart_esp_1
    tx_pin: 17
    rx_pin: 16
    baud_rate: 115200
    rx_buffer_size: 1000
