# Updated   : 2024.05.18
# Version   : 1.1
# GitHub    : https://github.com/Sleeper85/esphome-jk-bms-can
# Changelog : https://github.com/Sleeper85/esphome-jk-bms-can?tab=readme-ov-file#changelog

# JK-BMS-CAN ( PYLON, Seplos, GoodWe, SMA and Victron CAN bus protocol )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  name: smartbms

logger:
  #level: INFO

ota:
  
# Please use the native `api` component instead of the `mqtt` section.
# If you use Home Assistant, the native API is more lightweight.
# If there is no HA server connected to this API, the ESP32 reboots every 15 minutes to try to resolve the problem.
# If you don't use Home Assistant please uncomment the "reboot_timeout: 0s" option.
api:
  reboot_timeout: 0s

# If you don't want to use ESPHome's native API you can use MQTT instead.
# In this case don't forget to remove the 'api:' section.
# mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  id: mqtt_client

# In the event of problems with the WiFi network, the ESP32 will reboot every 15 minutes to try to resolve the problem.
# If we don't want to connect the ESP32 to the WiFi network please remove the 4 lines below.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

captive_portal:

#web_server:
#  port: 80
#  log: false
#  ota: false

# +--------------------------------------+
# | Packages                             |
# +--------------------------------------+
packages:
  # Board : uncomment your board
  # device_board: !include packages/board/board_esp32-devkit-v1.yaml
  # device_board: !include packages/board/board_esp32-s3-devkitc-1.yaml
  device_board: !include packages/board/board_atom-s3-lite.yaml
  
  # device_board: !include
  #   file: packages/board/board_atom-s3-display.yaml
  #   vars:
  #     smartbms_id: 'smartbms1'
  #     canbus_id: 'canbus1'

  device_base: !include packages/base/device_base.yaml

  # The sniffer represents the ESP node connected to the JK-BMS PB RS485 bus
  sniffer1: !include
    file: packages/bms/bms_jk-bms_rs485_pb_sniffer.yaml
    vars:
      sniffer_id: 'sniffer1'
      sniffer_protocol: 'JK02_32S'
      sniffer_uart_id: 'uart_esp_1'
      sniffer_talk_pin: 8

  # Configure the DIP switches of your BMS from 0x01 to 0x0F (don't use the 0x00 address, maximum 15 BMS)
  bms1: !include
    file: packages/bms/bms_jk-bms_rs485_pb_bms.yaml
    vars:
      # Smart BMS ID
      smartbms_id: 'smartbms1'
      # Sniffer ID
      sniffer_id: 'sniffer1'
      # BMS vars
      bms_id: '1' # must be a number
      bms_name: 'JK-BMS 1'
      bms_rs485_address: '0x00' # BMS 1 DIP switch
      bms_update_interval: "1s"
  
  bms2: !include
    file: packages/bms/bms_jk-bms_rs485_pb_bms.yaml
    vars:
      # Smart BMS ID
      smartbms_id: 'smartbms1'
      # Sniffer ID
      sniffer_id: 'sniffer1'
      # BMS vars
      bms_id: '2' # must be a number
      bms_name: 'JK-BMS 2'
      bms_rs485_address: '0x02' # BMS 2 DIP switch
      bms_update_interval: "1s"

  bms3: !include
    file: packages/bms/bms_jk-bms_rs485_pb_bms.yaml
    vars:
      # Smart BMS ID
      smartbms_id: 'smartbms1'
      # Sniffer ID
      sniffer_id: 'sniffer1'
      # BMS vars
      bms_id: '3' # must be a number
      bms_name: 'JK-BMS 3'
      bms_rs485_address: '0x03' # BMS 3 DIP switch
      bms_update_interval: "1s"

  bms4: !include
    file: packages/bms/bms_jk-bms_rs485_pb_bms.yaml
    vars:
      # Smart BMS ID
      smartbms_id: 'smartbms1'
      # Sniffer ID
      sniffer_id: 'sniffer1'
      # BMS vars
      bms_id: '4' # must be a number
      bms_name: 'JK-BMS 4'
      bms_rs485_address: '0x04' # BMS 4 DIP switch
      bms_update_interval: "1s"
  
  bms5: !include
    file: packages/bms/bms_jk-bms_rs485_pb_bms.yaml
    vars:
      # Smart BMS ID
      smartbms_id: 'smartbms1'
      # Sniffer ID
      sniffer_id: 'sniffer1'
      # BMS vars
      bms_id: '5' # must be a number
      bms_name: 'JK-BMS 5'
      bms_rs485_address: '0x05' # BMS 5 DIP switch
      bms_update_interval: "1s"

  bms6: !include
    file: packages/bms/bms_jk-bms_rs485_pb_bms.yaml
    vars:
      # Smart BMS ID
      smartbms_id: 'smartbms1'
      # Sniffer ID
      sniffer_id: 'sniffer1'
      # BMS vars
      bms_id: '6' # must be a number
      bms_name: 'JK-BMS 6'
      bms_rs485_address: '0x06' # BMS 6 DIP switch
      bms_update_interval: "1s"

  bms7: !include
    file: packages/bms/bms_jk-bms_rs485_pb_bms.yaml
    vars:
      # Smart BMS ID
      smartbms_id: 'smartbms1'
      # Sniffer ID
      sniffer_id: 'sniffer1'
      # BMS vars
      bms_id: '7' # must be a number
      bms_name: 'JK-BMS 7'
      bms_rs485_address: '0x07' # BMS 7 DIP switch
      bms_update_interval: "1s"
