# Updated : 2024.08.31
# Version : 1.0.2
# GitHub  : https://github.com/SeByDocKy/pvbrain2

substitutions:
  uart_hub_bus: 'spi'

spi:
  - id: spi0_bus
    mosi_pin: GPIO6  
    miso_pin: GPIO41
    clk_pin: GPIO40
    
wk2168_spi:
  - id: uart_bridge0
    spi_id: spi0_bus
    cs_pin: GPIO19
    data_rate: 4MHz
    #test_mode: 1
    uart:
      - id: uart_spi_0
        channel: 0
        baud_rate: ${uart0_baudrate}
        #parity: even
      - id: uart_spi_1
        channel: 1
        baud_rate: ${uart1_baudrate}
      - id: uart_spi_2
        channel: 2
        baud_rate: ${uart2_baudrate}
        #parity: even
      - id: uart_spi_3
        channel: 3
        baud_rate: ${uart3_baudrate}       
      
  - id: uart_bridge1
    spi_id: spi0_bus
    cs_pin: GPIO20
    data_rate: 4MHz
    uart:
      - id: uart_spi_4
        channel: 0
        baud_rate: ${uart4_baudrate}
        #parity: even
      - id: uart_spi_5
        channel: 1
        baud_rate: ${uart5_baudrate}
      - id: uart_spi_6
        channel: 2
        baud_rate: ${uart6_baudrate}
        #parity: even
      - id: uart_spi_7
        channel: 3
        baud_rate: ${uart7_baudrate}
