# Updated : 2024.08.31
# Version : 1.0.2
# GitHub  : https://github.com/SeByDocKy/pvbrain2

substitutions:
  uart_hub_bus: 'i2c'

i2c:
  - id: i2c1_bus
    sda: GPIO41 
    scl: GPIO40
    frequency: 800kHz
    
wk2168_i2c:
  - address: 0x10
    id: uart_bridge0
    i2c_id: i2c1_bus
    uart:
      - id: uart_i2c_0
        channel: 0
        baud_rate: ${uart0_baudrate}
        # parity: even
      - id: uart_i2c_1
        channel: 1
        baud_rate: ${uart1_baudrate}   
      - id: uart_i2c_2
        channel: 2
        baud_rate: ${uart2_baudrate}
        # parity: even
      - id: uart_i2c_3
        channel: 3
        baud_rate: ${uart3_baudrate}

  - address: 0x70
    id: uart_bridge1
    i2c_id: i2c1_bus
    uart:
      - id: uart_i2c_4
        channel: 0
        baud_rate: ${uart4_baudrate}
        # parity: even
      - id: uart_i2c_5
        channel: 1
        baud_rate: ${uart5_baudrate}
      - id: uart_i2c_6
        channel: 2
        baud_rate: ${uart6_baudrate}
        # parity: even
      - id: uart_i2c_7
        channel: 3
        baud_rate: ${uart7_baudrate}
