# Updated : 2024.07.29
# Version : 1.4.2
# GitHub  : https://github.com/SeByDocKy/pvbrain2

esphome:
  name: ${name}
  # friendly_name: ${name}
  # comment: 'Solar system braining and more !'
  # area: 'Local Technique'
  project:
    name: Sleeper85.YamBMS
    version: "1.4.2"
  min_version: 2024.6.3
  # Standard uses a single line for data, Dual IO uses 2 lines for data.
  platformio_options:
    board_build.flash_mode: dio               # Needed to flash the ESP32-S3 and prevent reboot loop
    board_upload.maximum_ram_size: 524288     # Total Size of the internal RAM in bits. It's the same for all ESP32-S3 ( 512KB )

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB # ajust according to your ESP32-S3 version
  framework:
    type: esp-idf

# PSRAM activation and settings
psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: USB_SERIAL_JTAG