# Version : 2024.04.01

# This YAML is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  bms_base: !include bms_base.yaml

external_components:
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s
  
ota:
  on_begin:
    then:
      - lambda: id(enable_bluetooth_connection).turn_off();
      - logger.log: "BLE shutdown for flashing"
  
# +--------------------------------------+
# | JK-BMS BLE connection                |
# +--------------------------------------+

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          if (x.get_name().rfind("JK-", 0) == 0) {
            ESP_LOGI("ble_adv", "New JK-BMS found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }

ble_client:
  - mac_address: ${bms_ble_mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${bms_ble_protocol_version}
    throttle: ${bms_update_interval}
    id: bms0

# +--------------------------------------+

binary_sensor:
  - platform: jk_bms_ble
    balancing:
      id: ${bms_id}_equalizing
      name: "${bms_name} balancing"
    charging:
      name: "${bms_name} charging"
    discharging:
      name: "${bms_name} discharging"
    online_status:
      name: "${bms_name} Online Status"

switch:
  - platform: jk_bms_ble
    charging:
      id: ${bms_id}_switch_charging
      name: "${bms_name} Charge switch"
    discharging:
      id: ${bms_id}_switch_discharging
      name: "${bms_name} Discharge switch"
    balancer:
      id: ${bms_id}_switch_balancing
      name: "${bms_name} Balance switch"
    # +--------------------------------------+
  - platform: ble_client
    ble_client_id: client0
    id: ${bms_id}_enable_bluetooth_connection
    name: "${bms_name} Enable Bluetooth connection"
    # +--------------------------------------+

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      id: ${bms_id}_min_cell_voltage
      name: "${bms_name} min cell voltage"
    max_cell_voltage:
      id: ${bms_id}_max_cell_voltage
      name: "${bms_name} max cell voltage"
    min_voltage_cell:
      id: ${bms_id}_min_voltage_cell
      name: "${bms_name} min voltage cell"
    max_voltage_cell:
      id: ${bms_id}_max_voltage_cell
      name: "${bms_name} max voltage cell"
    delta_cell_voltage:
      id: ${bms_id}_delta_cell_voltage
      name: "${bms_name} delta cell voltage"
    average_cell_voltage:
      name: "${bms_name} average cell voltage"
    cell_voltage_1:
      id: ${bms_id}_cell_v_01
      name: "${bms_name} cell voltage 01"
    cell_voltage_2:
      id: ${bms_id}_cell_v_02
      name: "${bms_name} cell voltage 02"
    cell_voltage_3:
      id: ${bms_id}_cell_v_03
      name: "${bms_name} cell voltage 03"
    cell_voltage_4:
      id: ${bms_id}_cell_v_04
      name: "${bms_name} cell voltage 04"
    cell_voltage_5:
      id: ${bms_id}_cell_v_05
      name: "${bms_name} cell voltage 05"
    cell_voltage_6:
      id: ${bms_id}_cell_v_06
      name: "${bms_name} cell voltage 06"
    cell_voltage_7:
      id: ${bms_id}_cell_v_07
      name: "${bms_name} cell voltage 07"
    cell_voltage_8:
      id: ${bms_id}_cell_v_08
      name: "${bms_name} cell voltage 08"
    cell_voltage_9:
      id: ${bms_id}_cell_v_09
      name: "${bms_name} cell voltage 09"
    cell_voltage_10:
      id: ${bms_id}_cell_v_10
      name: "${bms_name} cell voltage 10"
    cell_voltage_11:
      id: ${bms_id}_cell_v_11
      name: "${bms_name} cell voltage 11"
    cell_voltage_12:
      id: ${bms_id}_cell_v_12
      name: "${bms_name} cell voltage 12"
    cell_voltage_13:
      id: ${bms_id}_cell_v_13
      name: "${bms_name} cell voltage 13"
    cell_voltage_14:
      id: ${bms_id}_cell_v_14
      name: "${bms_name} cell voltage 14"
    cell_voltage_15:
      id: ${bms_id}_cell_v_15
      name: "${bms_name} cell voltage 15"
    cell_voltage_16:
      id: ${bms_id}_cell_v_16
      name: "${bms_name} cell voltage 16"
    cell_voltage_17:
      id: ${bms_id}_cell_v_17
      name: "${bms_name} cell voltage 17"
      disabled_by_default: true
    cell_voltage_18:
      id: ${bms_id}_cell_v_18
      name: "${bms_name} cell voltage 18"
      disabled_by_default: true
    cell_voltage_19:
      id: ${bms_id}_cell_v_19
      name: "${bms_name} cell voltage 19"
      disabled_by_default: true
    cell_voltage_20:
      id: ${bms_id}_cell_v_20
      name: "${bms_name} cell voltage 20"
      disabled_by_default: true
    cell_voltage_21:
      id: ${bms_id}_cell_v_21
      name: "${bms_name} cell voltage 21"
      disabled_by_default: true
    cell_voltage_22:
      id: ${bms_id}_cell_v_22
      name: "${bms_name} cell voltage 22"
      disabled_by_default: true
    cell_voltage_23:
      id: ${bms_id}_cell_v_23
      name: "${bms_name} cell voltage 23"
      disabled_by_default: true
    cell_voltage_24:
      id: ${bms_id}_cell_v_24
      name: "${bms_name} cell voltage 24"
      disabled_by_default: true
    cell_resistance_1:
      name: "${bms_name} cell resistance 01"
    cell_resistance_2:
      name: "${bms_name} cell resistance 02"
    cell_resistance_3:
      name: "${bms_name} cell resistance 03"
    cell_resistance_4:
      name: "${bms_name} cell resistance 04"
    cell_resistance_5:
      name: "${bms_name} cell resistance 05"
    cell_resistance_6:
      name: "${bms_name} cell resistance 06"
    cell_resistance_7:
      name: "${bms_name} cell resistance 07"
    cell_resistance_8:
      name: "${bms_name} cell resistance 08"
    cell_resistance_9:
      name: "${bms_name} cell resistance 09"
    cell_resistance_10:
      name: "${bms_name} cell resistance 10"
    cell_resistance_11:
      name: "${bms_name} cell resistance 11"
    cell_resistance_12:
      name: "${bms_name} cell resistance 12"
    cell_resistance_13:
      name: "${bms_name} cell resistance 13"
    cell_resistance_14:
      name: "${bms_name} cell resistance 14"
    cell_resistance_15:
      name: "${bms_name} cell resistance 15"
    cell_resistance_16:
      name: "${bms_name} cell resistance 16"
    #cell_resistance_17:
    #  name: "${bms_name} cell resistance 17"
    #cell_resistance_18:
    #  name: "${bms_name} cell resistance 18"
    #cell_resistance_19:
    #  name: "${bms_name} cell resistance 19"
    #cell_resistance_20:
    #  name: "${bms_name} cell resistance 20"
    #cell_resistance_21:
    #  name: "${bms_name} cell resistance 21"
    #cell_resistance_22:
    #  name: "${bms_name} cell resistance 22"
    #cell_resistance_23:
    #  name: "${bms_name} cell resistance 23"
    #cell_resistance_24:
    #  name: "${bms_name} cell resistance 24"
    total_voltage:
      id: ${bms_id}_total_voltage
      name: "${bms_name} total voltage"
    current:
      id: ${bms_id}_current
      name: "${bms_name} current"
    power:
      id: ${bms_id}_power
      name: "${bms_name} power"
    charging_power:
      id: ${bms_id}_charging_power
      name: "${bms_name} charging power"
    discharging_power:
      id: ${bms_id}_discharging_power
      name: "${bms_name} discharging power"
    power_tube_temperature:
      id: ${bms_id}_power_tube_temperature
      name: "${bms_name} power tube temperature"
    temperature_sensor_1:
      id: ${bms_id}_temperature_sensor_1
      name: "${bms_name} temperature sensor 1"
    temperature_sensor_2:
      id: ${bms_id}_temperature_sensor_2
      name: "${bms_name} temperature sensor 2"
    state_of_charge:
      id: ${bms_id}_state_of_charge
      name: "${bms_name} state of charge"
    capacity_remaining:
      id: ${bms_id}_capacity_remaining_ah
      name: "${bms_name} capacity remaining"
    total_battery_capacity_setting:
      id: ${bms_id}_battery_capacity
      name: "${bms_name} total battery capacity setting"
    charging_cycles:
      id: ${bms_id}_charging_cycles
      name: "${bms_name} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms_name} total charging cycle capacity"
    total_runtime:
      name: "${bms_name} total runtime"
    balancing_current:
      name: "${bms_name} balancing current"
    errors_bitmask:
      id: ${bms_id}_errors_bitmask
      name: "${bms_name} errors bitmask"

text_sensor:
  - platform: jk_bms_ble
    errors:
      name: "${bms_name} errors"
    total_runtime_formatted:
      name: "${bms_name} total runtime formatted"
      entity_category: diagnostic

number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      id: ${bms_id}_balance_trigger_voltage
      name: "${bms_name} balance trigger voltage"
    cell_count:
      id: ${bms_id}_cell_count
      name: "${bms_name} cell count"
    total_battery_capacity:
      name: "${bms_name} total battery capacity"
    cell_voltage_overvoltage_protection:
      id: ${bms_id}_cell_ovp
      name: "${bms_name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      id: ${bms_id}_cell_ovpr
      name: "${bms_name} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      id: ${bms_id}_cell_uvp
      name: "${bms_name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      id: ${bms_id}_cell_uvpr
      name: "${bms_name} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${bms_name} balance starting voltage"
    voltage_calibration:
      name: "${bms_name} voltage calibration"
    current_calibration:
      name: "${bms_name} current calibration"
    power_off_voltage:
      name: "${bms_name} power off voltage"
    max_balance_current:
      name: "${bms_name} max balance current"
    max_charge_current:
      name: "${bms_name} max charge current"
    max_discharge_current:
      name: "${bms_name} max discharge current"

button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${bms_name} retrieve settings"
      entity_category: config
    retrieve_device_info:
      name: "${bms_name} retrieve device info"
      entity_category: config
