# Updated : 2024.05.15
# Version : 1.1
# GitHub  : https://github.com/Sleeper85/esphome-jk-bms-can

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB # ajust according to your ESP32-S3 version
  framework:
    type: esp-idf

esphome:
  # Dual IO uses 2 lines for data
  # Standard uses a single line for data
  # The firmware flash only works in "dio" mode for my ESP32-S3 "N16R8", otherwise endless loop and reboot
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    then:
      - light.turn_on:
          id: esp_light
          red: 50%
          blue: 50%
          green: 0%
          brightness: 50%

uart:
  # UART 0 : uart used for ESP32 flashing and logs, can be released if necessary (tx_pin: 43, rx_pin: 44)
  # UART 1 : BMS 1
  - id: uart_esp_1
    tx_pin: 17
    rx_pin: 18
    baud_rate: 115200
    rx_buffer_size: 384
  # UART 2 : BMS 2
  - id: uart_esp_2
    tx_pin: 15
    rx_pin: 16
    baud_rate: 115200
    rx_buffer_size: 384

canbus:
  # CANBUS NODE 1
  - platform: esp32_can
    id: canbus_node1
    tx_pin: 38
    rx_pin: 39
    can_id: 1
    bit_rate: 500kbps

light:
  # https://esphome.io/components/light/esp32_rmt_led_strip
  - platform: esp32_rmt_led_strip
    id: esp_light
    name: ${name} ESP Light
    rgb_order: GRB
    pin: 48
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    entity_category: config
    internal: true