# +--------------------------------------+
# | ESP32 device settings                |
# +--------------------------------------+
substitutions:
  # GPIO pins your JK-BMS UART-TTL is connected to the ESP32 TX->RX and RX->TX !
  bms_tx_pin: GPIO17
  bms_rx_pin: GPIO16
  # GPIO pins your CAN bus transceiver (TJA1050, TJA1051T or SN65HVD230) is connected to the ESP32 TX->TX and RX->RX !
  canbus_tx_pin: GPIO23
  canbus_rx_pin: GPIO22

# For a stable Bluetooth connection keep the "esp-idf" framework
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

output:
  - platform: gpio
    pin: 2
    id: led
    inverted: true

light:
  - platform: binary
    output: led
    id: can_status_led
    name: "Blue LED"
    internal: true