# Updated : 2024.04.03
# Version : 1.1.1
# Owner   : Sleeper85

# This YAML is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# TODO !
# id(bms1_switch_balancing).state
# id(bms1_errors_bitmask).state
# id(bms1_min_voltage_cell).state
# id(bms1_max_voltage_cell).state
# auto_cvl : id(bms1_cell_v_01).state to id(bms1_cell_v_24).state

globals:
  - id: ${smart_bms_id}_bms_counter
    type: int
    restore_value: no
    initial_value: '0'
  - id: ${smart_bms_id}_combined_bms_counter
    type: int
    restore_value: no
    initial_value: '0'
  - id: ${smart_bms_id}_equalizing_counter
    type: int
    restore_value: no
    initial_value: '0'
  - id: ${smart_bms_id}_total_cell_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: ${smart_bms_id}_total_max_charge_current
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_total_max_discharge_current
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_min_min_cell_voltage
    type: float
    restore_value: no
    initial_value: '5.0'
  - id: ${smart_bms_id}_max_max_cell_voltage
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_total_total_voltage
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_total_current
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_total_power
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_total_soc
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_total_capacity_remaining_ah
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_total_battery_capacity
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_total_charging_cycles
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_min_cell_ovp
    type: float
    restore_value: no
    initial_value: '5.0'
  - id: ${smart_bms_id}_min_cell_ovpr
    type: float
    restore_value: no
    initial_value: '5.0'
  - id: ${smart_bms_id}_max_cell_uvpr
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_max_temperature_sensor_1
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ${smart_bms_id}_max_temperature_sensor_2
    type: float
    restore_value: no
    initial_value: '0.0'

# Combine continuously
interval:
  - interval: 1s
    then:
      - lambda: |-
          if (id(${smart_bms_id}_combined_bms_counter) == id(${smart_bms_id}_bms_counter)) {

            // total_voltage MEAN
            float total_voltage = 0.0;
            if (id(${smart_bms_id}_bms_counter) > 0) total_voltage = (id(${smart_bms_id}_total_total_voltage) / id(${smart_bms_id}_bms_counter));
            id(${smart_bms_id}_total_voltage).publish_state(total_voltage);
            id(${smart_bms_id}_total_total_voltage) = 0.0;
            
            // current SUM
            id(${smart_bms_id}_current).publish_state(id(${smart_bms_id}_total_current));
            id(${smart_bms_id}_total_current) = 0.0;
            
            // power SUM
            id(${smart_bms_id}_power).publish_state(id(${smart_bms_id}_total_power));
            id(${smart_bms_id}_total_power) = 0.0;
            
            // state_of_charge MEAN
            float soc = 0.0;
            if (id(${smart_bms_id}_bms_counter) > 0) soc = (id(${smart_bms_id}_total_soc) / id(${smart_bms_id}_bms_counter));
            id(${smart_bms_id}_state_of_charge).publish_state(soc);
            id(${smart_bms_id}_total_soc) = 0.0;
            
            // capacity_remaining_ah SUM
            id(${smart_bms_id}_capacity_remaining_ah).publish_state(id(${smart_bms_id}_total_capacity_remaining_ah));
            id(${smart_bms_id}_total_capacity_remaining_ah) = 0.0;
            
            // charging_cycles MEAN
            float charging_cycles = 0.0;
            if (id(${smart_bms_id}_bms_counter) > 0) charging_cycles = (id(${smart_bms_id}_total_charging_cycles) / id(${smart_bms_id}_bms_counter));
            id(${smart_bms_id}_charging_cycles).publish_state(charging_cycles);
            id(${smart_bms_id}_total_charging_cycles) = 0.0;
            
            // Reset combined_bms_counter
            id(${smart_bms_id}_combined_bms_counter) = 0;
          }

binary_sensor:
  # Balancing state (global = true if any BMS is balancing)
  - platform: template
    name: "${smart_bms_name} Equalizing State"
    id: ${smart_bms_id}_equalizing
    lambda: return (id(${smart_bms_id}_equalizing_counter) > 0);

sensor:
  # cell_count
  - platform: template
    id: ${smart_bms_id}_cell_count
    name: "${smart_bms_name} Cell Count"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 0
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return id(${smart_bms_id}_total_cell_count);

  # max_charge_current SUM
  - platform: template
    id: ${smart_bms_id}_max_charge_current
    name: "${smart_bms_name} Max Charge current (Σ)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: A
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return id(${smart_bms_id}_total_max_charge_current);

  # max_discharge_current SUM
  - platform: template
    id: ${smart_bms_id}_max_discharge_current
    name: "${smart_bms_name} Max Discharge Current (Σ)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: A
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return id(${smart_bms_id}_total_max_discharge_current);

  # min_cell_voltage MIN
  - platform: template
    id: ${smart_bms_id}_min_cell_voltage
    name: "${smart_bms_name} Min Cell Voltage"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: |-
      if (id(${smart_bms_id}_bms_counter) == 0) id(${smart_bms_id}_min_min_cell_voltage) = 5.0;
      return id(${smart_bms_id}_min_min_cell_voltage);

  # max_cell_voltage MAX
  - platform: template
    id: ${smart_bms_id}_max_cell_voltage
    name: "${smart_bms_name} Max Cell Voltage"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: |-
      if (id(${smart_bms_id}_bms_counter) == 0) id(${smart_bms_id}_max_max_cell_voltage) = 0.0;
      return id(${smart_bms_id}_max_max_cell_voltage);

  # total_voltage MEAN
  - platform: template
    id: ${smart_bms_id}_total_voltage
    name: "${smart_bms_name} Total Voltage (Ø)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 2
    unit_of_measurement: V
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001

  # current SUM
  - platform: template
    id: ${smart_bms_id}_current
    name: "${smart_bms_name} Current (Σ)"
    update_interval: ${smart_bms_update_interval}
    unit_of_measurement: A
    filters:
      - or:
        - throttle: 10s
        - delta: 1

  # power SUM
  - platform: template
    id: ${smart_bms_id}_power
    name: "${smart_bms_name} Power (Σ)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: W
    filters:
      - or:
        - throttle: 10s
        - delta: 1

  # temperature_sensor_1 MAX
  - platform: template
    id: ${smart_bms_id}_temperature_sensor_1
    name: "${smart_bms_name} Temperature Sensor 1"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 2
    unit_of_measurement: °C
    lambda: |-
      if (id(${smart_bms_id}_bms_counter) == 0) id(${smart_bms_id}_max_temperature_sensor_1) = 0.0;
      return id(${smart_bms_id}_max_temperature_sensor_1);

  # temperature_sensor_2 MAX
  - platform: template
    id: ${smart_bms_id}_temperature_sensor_2
    name: "${smart_bms_name} Temperature Sensor 2"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 2
    unit_of_measurement: °C
    lambda: |-
      if (id(${smart_bms_id}_bms_counter) == 0) id(${smart_bms_id}_max_temperature_sensor_2) = 0.0;
      return id(${smart_bms_id}_max_temperature_sensor_2);

# power_tube_temperature MIN_MAX
# - platform: template
#   id: ${smart_bms_id}_power_tube_temperature
#   name: "${smart_bms_name} power_tube_temperature"
#   update_interval: ${smart_bms_update_interval}
#   accuracy_decimals: 2
#   unit_of_measurement: °C

  # state_of_charge MEAN
  - platform: template
    id: ${smart_bms_id}_state_of_charge
    name: "${smart_bms_name} SOC (Ø)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: '%'
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001

  # capacity_remaining_ah SUM
  - platform: template
    id: ${smart_bms_id}_capacity_remaining_ah
    name: "${smart_bms_name} Capacity Remaining (Σ)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: Ah
    filters:
      - or:
        - throttle: 10s
        - delta: 1

  # battery_capacity SUM
  - platform: template
    id: ${smart_bms_id}_battery_capacity
    name: "${smart_bms_name} Battery Capacity Total (Σ)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: Ah
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return id(${smart_bms_id}_total_battery_capacity);

  # charging_cycles MEAN
  - platform: template
    id: ${smart_bms_id}_charging_cycles
    name: "${smart_bms_name} Charging Cycles (Ø)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 0
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001

  # cell_ovp MIN
  - platform: template
    id: ${smart_bms_id}_cell_ovp
    name: "${smart_bms_name} Cell OVP (MIN)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 3
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: |-
      if (id(${smart_bms_id}_bms_counter) == 0) id(${smart_bms_id}_min_cell_ovp) = 5.0;
      float min_cell_ovp = id(${smart_bms_id}_min_cell_ovp);
      // sets the sliders max value to the BMS cell_ovp * cell_count
      id(${smart_bms_id}_bulk_voltage).traits.set_max_value(min_cell_ovp * id(${smart_bms_id}_cell_count).state);
      id(${smart_bms_id}_float_voltage).traits.set_max_value(min_cell_ovp * id(${smart_bms_id}_cell_count).state);
      id(${smart_bms_id}_rebulk_voltage).traits.set_max_value(min_cell_ovp * id(${smart_bms_id}_cell_count).state);
      return min_cell_ovp;

  # cell_ovpr MIN
  - platform: template
    id: ${smart_bms_id}_cell_ovpr
    name: "${smart_bms_name} Cell OVPR (MIN)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 3
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: |-
      if (id(${smart_bms_id}_bms_counter) == 0) id(${smart_bms_id}_min_cell_ovpr) = 5.0;
      return id(${smart_bms_id}_min_cell_ovpr);

  # cell_uvr MAX
  - platform: template
    id: ${smart_bms_id}_cell_uvpr
    name: "${smart_bms_name} Cell UVPR (MAX)"
    update_interval: ${smart_bms_update_interval}
    accuracy_decimals: 3
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: |-
      if (id(${smart_bms_id}_bms_counter) == 0) id(${smart_bms_id}_max_cell_uvpr) = 0.0;
      return id(${smart_bms_id}_max_cell_uvpr);

  # Charge_Current_max SUM
#  - platform: template
#    id: ${smart_bms_id}_charging_current
#    name: "${smart_bms_name} CCL (Σ)"
#    update_interval: ${smart_bms_update_interval}
#    accuracy_decimals: 0
#    unit_of_measurement: A
#    filters:
#      - or:
#        - throttle: 10s
#        - delta: 1

  # Disharge_Current_max SUM
#  - platform: template
#    id: ${smart_bms_id}_discharging_current
#    name: "${smart_bms_name} DCL (Σ)"
#    update_interval: ${smart_bms_update_interval}
#    accuracy_decimals: 0
#    unit_of_measurement: A
#    filters:
#      - or:
#        - throttle: 10s
#        - delta: 1
